name: Gradle Build
description: Runs tests, lints, coverage, and SonarCloud scan

runs:
  using: composite
  steps:
    - name: Run Tests
      shell: bash
      run: ./gradlew test --no-daemon

    - name: Run Checkstyle Linter
      shell: bash
      run: ./gradlew checkstyleMain checkstyleTest --no-daemon

    - name: Generate JaCoCo Coverage Report
      shell: bash
      run: ./gradlew jacocoTestReport --no-daemon

    - name: Cache SonarCloud packages
      if: ${{ env.SONAR_TOKEN != '' && env.SONAR_PROJECT_KEY != '' && env.SONAR_ORGANIZATION != '' }}
      uses: actions/cache@v4
      with:
        path: .sonar/cache
        key: ${{ runner.os }}-sonar
        restore-keys: |
          ${{ runner.os }}-sonar

    - name: SonarCloud Scan (wait for Quality Gate)
      if: ${{ env.SONAR_TOKEN != '' && env.SONAR_PROJECT_KEY != '' && env.SONAR_ORGANIZATION != '' }}
      uses: SonarSource/sonarcloud-github-action@v2
      env:
        GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ env.SONAR_TOKEN }}
        SONAR_USER_HOME: ${{ github.workspace }}/.sonar
      with:
        args: >
          -Dsonar.projectKey=${{ env.SONAR_PROJECT_KEY }}
          -Dsonar.organization=${{ env.SONAR_ORGANIZATION }}
          -Dsonar.host.url=${{ env.SONAR_HOST_URL }}
          -Dsonar.sources=src/main/java
          -Dsonar.tests=src/test/java
          -Dsonar.java.binaries=build/classes/java/main
          -Dsonar.java.test.binaries=build/classes/java/test
          -Dsonar.junit.reportPaths=build/test-results/test
          -Dsonar.coverage.jacoco.xmlReportPaths=build/reports/jacoco/test/jacocoTestReport.xml

